/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientep2p;

/**
 *
 * @author angel
 */
public class VChat extends javax.swing.JFrame {
    
    public ClientInterface myClientInterface;
    public String myUserID;
    public ClientInterface othersClientInterface;
    public String myFriendsUserID;
    
    

    /**
     * Creates new form VChat
     */
    public VChat(ClientInterface myClientInterface, String myUserID, ClientInterface othersClientInterface, String myFriendsUserID) {
        initComponents();
        this.setDefaultCloseOperation(VChat.DISPOSE_ON_CLOSE);
        this.myClientInterface=myClientInterface;
        this.myUserID= myUserID;
        this.othersClientInterface=othersClientInterface;
        this.myFriendsUserID=myFriendsUserID;
        myName.setText(myUserID);
        myFriendsName.setText(myFriendsUserID);
        areaDeMensajesDelChat.setEditable(false);
    }
    
    public VChat(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        areaDeMensajesDeSalida = new javax.swing.JTextField();
        areaDeMensajesDelChat = new javax.swing.JTextField();
        jButton_enviarMensaje = new javax.swing.JButton();
        jButton_irAVistaPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        myFriendsName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        myName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/Bonita-PNG.png"))); // NOI18N

        jButton_enviarMensaje.setText("Enviar mensaje");

        jButton_irAVistaPrincipal.setText("Finalizar chat");

        jLabel1.setText("Estas chateando con:");

        myFriendsName.setText("Nombre del usuario");

        jLabel2.setText("Hola: ");

        myName.setText("yo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jButton_enviarMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton_irAVistaPrincipal)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(myFriendsName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(areaDeMensajesDeSalida)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaDeMensajesDelChat, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(myName)))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton_irAVistaPrincipal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(myName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(myFriendsName))
                .addGap(43, 43, 43)
                .addComponent(areaDeMensajesDelChat, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(areaDeMensajesDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_enviarMensaje)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTextChat(String texto){
        areaDeMensajesDelChat.setText(texto);
    }
    public String getTextChat(){
        return areaDeMensajesDelChat.getText();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaDeMensajesDeSalida;
    private javax.swing.JTextField areaDeMensajesDelChat;
    private javax.swing.JButton jButton_enviarMensaje;
    private javax.swing.JButton jButton_irAVistaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel myFriendsName;
    private javax.swing.JLabel myName;
    // End of variables declaration//GEN-END:variables
}
