/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientep2p;

import java.rmi.RemoteException;

/**
 *
 * @author angel
 */
public class VPeticionAmistad extends javax.swing.JFrame {

    private String myUserID;
    private String password;
    private String othersUserID;
    private ServerInterface servidor;
    
    public VPeticionAmistad(String myUserID, String password, String othersUserID, ServerInterface servidor) {
        initComponents();
        this.setDefaultCloseOperation(VPeticionAmistad.DISPOSE_ON_CLOSE);
        this.myUserID = myUserID;
        this.servidor = servidor;
        this.othersUserID = othersUserID;
        this.password = password;
        jLabelAmigo.setText("El usuario "+othersUserID+ " te ha enviado una peticion de amistad ");
    }
    
    /**
     * Creates new form VPeticionAmistad
     */
    public VPeticionAmistad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAmigo = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bRechazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bRechazar.setText("Rechazar");
        bRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bAceptar)
                        .addGap(73, 73, 73)
                        .addComponent(bRechazar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bRechazar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            servidor.acceptFriendRequest(myUserID, password, othersUserID);
            this.setVisible(false);
        } catch (RemoteException ex) {
            System.out.println("Excepcion al aceptar una peticion de amistad: "+ex.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRechazarActionPerformed
        try {
            servidor.denyFriendRequest(myUserID,password,othersUserID);
            this.setVisible(false);
        } catch (RemoteException ex) {
            System.out.println("Excepcion al rechazar una peticion de amistad: "+ex.getMessage());
        }
    }//GEN-LAST:event_bRechazarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bRechazar;
    private javax.swing.JLabel jLabelAmigo;
    // End of variables declaration//GEN-END:variables
}
