/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientep2p;

import java.awt.Label;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author angel
 */
public class VPrincipal extends javax.swing.JFrame {
    
    public static ClientInterface cliente;
    private ServerInterface servidor;
    public String userID;
    private String password;
    public Map<String, ClientInterface> friendsConnected;
    private ArrayList<String> friendRequests;

    public VPrincipal(ClientInterface cliente, ServerInterface servidor, String userID, String password, Map<String, ClientInterface> friendsConnected) throws RemoteException {
        initComponents();
        this.cliente=cliente;
        this.servidor=servidor;
        this.userID=userID;
        this.password=password;
        this.friendsConnected=friendsConnected;
        this.friendRequests = new ArrayList<>();
    }
       
    
    public VPrincipal() throws RemoteException {
        initComponents();
    }

    public void updateFriendRequests(ArrayList<String> requests){
        this.friendRequests=requests;
        this.jButton_peticionesPendientes.setText(requests.size() + "Peticiones de amistad pendientes");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        textoBusquedaDeUsuarios = new javax.swing.JTextField();
        jButton_buscarUsuarios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane_ResultadoBusquedaUsuarios = new javax.swing.JScrollPane();
        jList_ResultadoBusquedaUsuarios = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton_enviarPeticionAmistad = new javax.swing.JButton();
        jButton_iniciarChat = new javax.swing.JButton();
        jScrollPane_ListaAmigosDelUsuario = new javax.swing.JScrollPane();
        jList_ListaAmigosDelUsuario = new javax.swing.JList<>();
        jButton_eliminarAmistad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane_AmigosConectados = new javax.swing.JScrollPane();
        jList_AmigosConectados = new javax.swing.JList<>();
        jButton_peticionesPendientes = new javax.swing.JButton();

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("label1");

        label3.setText("label3");

        jLabel2.setText("Amigos conectados");

        textoBusquedaDeUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoBusquedaDeUsuariosKeyReleased(evt);
            }
        });

        jButton_buscarUsuarios.setText("Buscar");
        jButton_buscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarUsuariosActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jList_ResultadoBusquedaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_ResultadoBusquedaUsuarios.setViewportView(jList_ResultadoBusquedaUsuarios);

        jLabel4.setText("Lista de amigos");

        jButton_enviarPeticionAmistad.setText("Enviar petición");
        jButton_enviarPeticionAmistad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enviarPeticionAmistadActionPerformed(evt);
            }
        });

        jButton_iniciarChat.setText("Iniciar Chat");
        jButton_iniciarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciarChatActionPerformed(evt);
            }
        });

        jList_ListaAmigosDelUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_ListaAmigosDelUsuario.setViewportView(jList_ListaAmigosDelUsuario);

        jButton_eliminarAmistad.setText("Eliminar amistad");
        jButton_eliminarAmistad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarAmistadActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar usuarios");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/Bonita-PNG.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jList_AmigosConectados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_AmigosConectados.setViewportView(jList_AmigosConectados);

        jButton_peticionesPendientes.setText("Peticiones pendientes");
        jButton_peticionesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_peticionesPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jButton_iniciarChat)))
                                .addGap(255, 255, 255))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane_AmigosConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196)))
                        .addGap(211, 211, 211))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_ListaAmigosDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton_eliminarAmistad))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4)))
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jButton_enviarPeticionAmistad))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoBusquedaDeUsuarios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_buscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane_ResultadoBusquedaUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_peticionesPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane_AmigosConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_iniciarChat)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane_ListaAmigosDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton_buscarUsuarios)
                                            .addComponent(textoBusquedaDeUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jButton_enviarPeticionAmistad)
                                                    .addComponent(jButton_eliminarAmistad)))
                                            .addComponent(jScrollPane_ResultadoBusquedaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(jButton_peticionesPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_peticionesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_peticionesPendientesActionPerformed
        
        VPeticionAmistad nuevaPeticion;
        
        for (String solicitanteDeAmistad : this.friendRequests){
        
            nuevaPeticion = new VPeticionAmistad(this.userID, this.password, solicitanteDeAmistad, this.servidor);
            nuevaPeticion.setVisible(true);
        }
        
        this.updateFriendRequests(new ArrayList<String>());
    }//GEN-LAST:event_jButton_peticionesPendientesActionPerformed

    private void jButton_iniciarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciarChatActionPerformed
        
            try {
                if(!this.jList_AmigosConectados.isSelectionEmpty()){
                    //Obtenemos el userID del amigo seleccionado para obtener el acceso a su interfaz
                    String userID_de_mi_amigo = this.jList_AmigosConectados.getSelectedValue();
                    ClientInterface amigo = this.friendsConnected.get(userID_de_mi_amigo);

                    //Iniciamos un chat entre los dos amigos
                    cliente.startChat(amigo, userID_de_mi_amigo);
                    amigo.startChat(cliente, userID);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton_iniciarChatActionPerformed

    private void jButton_enviarPeticionAmistadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enviarPeticionAmistadActionPerformed
        
        try {
            if(!jList_ResultadoBusquedaUsuarios.isSelectionEmpty())
                this.servidor.friendRequest(userID, password, jList_ResultadoBusquedaUsuarios.getSelectedValue().toString());
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_enviarPeticionAmistadActionPerformed

    private void jButton_eliminarAmistadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarAmistadActionPerformed
        
        try {
            if(!this.jList_ListaAmigosDelUsuario.isSelectionEmpty()){
            
                boolean eliminado = false;
                String userID_ExAmigo = this.jList_ListaAmigosDelUsuario.getSelectedValue().toString();
                ArrayList<String> amigos = cliente.getListOfFriends();
                
                for(int i=0; i<amigos.size() && eliminado==false; i++){
                
                    if(amigos.get(i).toString().equals(userID_ExAmigo)){
                    
                        this.servidor.deleteFriend(userID_ExAmigo, userID, password);
                        eliminado=true;
                    }
                }
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_eliminarAmistadActionPerformed

    private void jButton_buscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarUsuariosActionPerformed
        
        List<String> listaBusquedaDeUsuarios = new ArrayList<>();
        try{
        
            listaBusquedaDeUsuarios = this.servidor.findFriend(this.textoBusquedaDeUsuarios.getText());
        }catch(RemoteException ex){
            System.out.println("Excepcion al buscar usuarios: "+ex.getMessage());
        }
        
        DefaultListModel listModel =new DefaultListModel();
        for(int i=0;i<listaBusquedaDeUsuarios.size();i++){
            listModel.add(i, listaBusquedaDeUsuarios.get(i));
        }
        this.jList_ResultadoBusquedaUsuarios.setModel(listModel);
        
        
    }//GEN-LAST:event_jButton_buscarUsuariosActionPerformed

    private void textoBusquedaDeUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoBusquedaDeUsuariosKeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            List<String> listaUsuarios=new ArrayList<>();
            try{
                listaUsuarios = servidor.findFriend(this.textoBusquedaDeUsuarios.getText());
            }catch(RemoteException ex){
                System.out.println("Excepcion al buscar usuarios: "+ex.getMessage());
            }

            DefaultListModel listModel = new DefaultListModel();
            for(int i=0; i<listaUsuarios.size(); i++){
                listModel.add(i, listaUsuarios.get(i));
            }
            this.jList_ResultadoBusquedaUsuarios.setModel(listModel);

        }
    }//GEN-LAST:event_textoBusquedaDeUsuariosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscarUsuarios;
    private javax.swing.JButton jButton_eliminarAmistad;
    private javax.swing.JButton jButton_enviarPeticionAmistad;
    private javax.swing.JButton jButton_iniciarChat;
    private javax.swing.JButton jButton_peticionesPendientes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JList<String> jList_AmigosConectados;
    public javax.swing.JList<String> jList_ListaAmigosDelUsuario;
    public javax.swing.JList<String> jList_ResultadoBusquedaUsuarios;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane_AmigosConectados;
    public javax.swing.JScrollPane jScrollPane_ListaAmigosDelUsuario;
    public javax.swing.JScrollPane jScrollPane_ResultadoBusquedaUsuarios;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField textoBusquedaDeUsuarios;
    // End of variables declaration//GEN-END:variables
}
